# Generated by Django 3.0 on 2019-12-03 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit_career',
            fields=[
                ('audit_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('career_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_id_name', to='career.Career')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
            options={
                'db_table': 'audit_career',
            },
        ),
        migrations.CreateModel(
            name='Plan_skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_skill', models.CharField(default='default', max_length=500)),
                ('skill_type', models.CharField(default='default', max_length=500)),
                ('skill_content', models.CharField(default='default', max_length=500)),
                ('userid', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
            options={
                'db_table': 'plan_skill',
            },
        ),
        migrations.CreateModel(
            name='Plan_licence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_licence', models.CharField(default='default', max_length=500)),
                ('userid', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
            options={
                'db_table': 'plan_licence',
            },
        ),
        migrations.CreateModel(
            name='Plan_attitude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_attitude', models.CharField(default='default', max_length=500)),
                ('userid', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
            options={
                'db_table': 'plan_attitude',
            },
        ),
        migrations.CreateModel(
            name='Member_love',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='love_career_id_name', to='career.Career')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
            options={
                'db_table': 'member_love',
            },
        ),
        migrations.CreateModel(
            name='Audit_skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('audit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.Audit_career')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_id_name', to='career.Career_skill')),
                ('userid', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
            options={
                'db_table': 'audit_skill',
            },
        ),
        migrations.CreateModel(
            name='Audit_personality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_personality_R', models.FloatField(max_length=10)),
                ('audit_personality_I', models.FloatField(max_length=10)),
                ('audit_personality_A', models.FloatField(max_length=10)),
                ('audit_personality_S', models.FloatField(max_length=10)),
                ('audit_personality_E', models.FloatField(max_length=10)),
                ('audit_personality_C', models.FloatField(max_length=10)),
                ('userid', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
            options={
                'db_table': 'audit_personality',
            },
        ),
        migrations.CreateModel(
            name='Audit_licence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.BooleanField()),
                ('audit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.Audit_career')),
                ('licence_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licence_id_name', to='career.Career_licence')),
                ('userid', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
            options={
                'db_table': 'audit_licence',
            },
        ),
        migrations.CreateModel(
            name='Audit_attitude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('attitude_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attitude_id_name', to='career.Career_attitude')),
                ('audit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.Audit_career')),
                ('userid', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
            options={
                'db_table': 'audit_attitude',
            },
        ),
    ]
