# Generated by Django 3.0 on 2019-12-03 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('career_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('career_name', models.CharField(max_length=100)),
                ('field', models.CharField(max_length=100)),
                ('career_type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'career',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('userid', models.CharField(max_length=100)),
                ('message_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200)),
                ('time', models.DateTimeField()),
                ('career_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.Career')),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='Career_skill',
            fields=[
                ('skill_id', models.AutoField(max_length=180, primary_key=True, serialize=False)),
                ('career_skill', models.CharField(max_length=100)),
                ('skill_type', models.CharField(max_length=100)),
                ('skill_content', models.CharField(max_length=140)),
                ('career_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.Career')),
            ],
            options={
                'db_table': 'career_skill',
            },
        ),
        migrations.CreateModel(
            name='Career_personality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personality_R', models.FloatField(max_length=10)),
                ('personality_I', models.FloatField(max_length=10)),
                ('personality_A', models.FloatField(max_length=10)),
                ('personality_S', models.FloatField(max_length=10)),
                ('personality_E', models.FloatField(max_length=10)),
                ('personality_C', models.FloatField(max_length=10)),
                ('career_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.Career')),
            ],
            options={
                'db_table': 'career_personality',
            },
        ),
        migrations.CreateModel(
            name='Career_licence',
            fields=[
                ('licence_id', models.AutoField(max_length=180, primary_key=True, serialize=False)),
                ('career_licence', models.CharField(max_length=100)),
                ('career_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.Career')),
            ],
            options={
                'db_table': 'career_licence',
            },
        ),
        migrations.CreateModel(
            name='Career_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_info', models.CharField(max_length=500)),
                ('career_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.Career')),
            ],
            options={
                'db_table': 'career_info',
            },
        ),
        migrations.CreateModel(
            name='Career_fucture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_fucture', models.CharField(max_length=100)),
                ('career_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.Career')),
            ],
            options={
                'db_table': 'career_fucture',
            },
        ),
        migrations.CreateModel(
            name='Career_attitude',
            fields=[
                ('attitude_id', models.AutoField(max_length=100, primary_key=True, serialize=False)),
                ('career_attitude', models.CharField(max_length=100)),
                ('career_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.Career')),
            ],
            options={
                'db_table': 'career_attitude',
            },
        ),
    ]
